server:
  port: 8088

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-task-test
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      #执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: -1
    accessToken:
